#!/bin/sh
#
# @name Gazebo x500 depth
#
# @type Quadrotor
#

PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_depth}

. ${R}etc/init.d-posix/airframes/4001_gz_x500

# Modifications
param set-default UXRCE_DDS_SYNCT 0

# Do not need external ground control station
param set-default NAV_DLL_ACT 0
param set-default NAV_RCL_ACT 0

# Deactivate battery failsafe
param set-default COM_LOW_BAT_ACT 0